<?php

namespace PiggyBox\OrderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    public function getOrderByShop($shopId)
    {
    $query = $this->getEntityManager()
            ->createQuery('SELECT o FROM PiggyBoxOrderBundle:Order o JOIN o.shop s WHERE s.id = :shopId')
            ->setParameter('shopId', $shopId);
    try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
    }

    public function getDetailCartByShopAndCart($shopId,$cartId)
    {
    return $this->getEntityManager()
            ->createQuery('SELECT c, o, s FROM PiggyBoxOrderBundle:Cart c LEFT JOIN c.orders o LEFT JOIN o.shop s WHERE (s.id=:shopId AND c.id=:cartId)')
            ->setParameter('shopId', $shopId)
            ->setParameter('cartId', $cartId)
            ->getResult();
    }

    /**
     * Find cart by session left join orders and order details and products
     *
     * */
    public function findBySession($cartId)
    {
    return $this->getEntityManager()
            ->createQuery('SELECT c, o, d, p FROM PiggyBoxOrderBundle:Cart c LEFT JOIN c.orders  o LEFT JOIN o.order_detail d LEFT JOIN d.product p WHERE c.id=:cart_id')
            ->setParameter('cart_id', $cartId)
            ->getSingleResult();
    }
}
