<?php

namespace PiggyBox\OrderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends EntityRepository
{
}
