<?php

namespace PiggyBox\OrderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getCartAndOrderByShop($shop_id, $cart_id)
    {
    return $this->getEntityManager()
            ->createQuery('SELECT DISTINCT o, s FROM PiggyBoxOrderBundle:Order o LEFT JOIN o.shop s  WHERE EXISTS (SELECT c FROM PiggyBoxOrderBundle:Cart c WHERE (c.id=:cart_id AND s.id=:shop_id))')
            ->setParameter('shop_id', $shop_id)
            ->setParameter('cart_id', $cart_id)
            ->getResult();
    }

    public function getOrdersByUser($user_id)
    {
    return $this->getEntityManager()
            ->createQuery('SELECT o, d, p FROM PiggyBoxOrderBundle:Order o LEFT JOIN o.order_detail d LEFT JOIN d.product p WHERE (o.status=\'toValidate\' AND o.user=:user_id)')
            ->setParameter('user_id', $user_id)
            ->getResult();
    }
}
