parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     piggybox_prod_v2 
    database_user:     piggyboxer2
    database_password: 66ln8^VeOwnLD8

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            grosseputesodomite
