parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     piggybox_mvp 
    database_user:     root
<<<<<<< HEAD
    database_password: 
=======
    database_password: root
>>>>>>> origin/develop

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
