parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     piggybox_prod
    database_user:     piggyboxer
    database_password: 66ln8^VeOwnLD8&Vk8

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            grosseputesodomite
