jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl: 
        connection: default

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, my_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_facebook_provider:
            id: my.facebook.user

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer: true
            fos_facebook:
                app_url: "http://apps.facebook.com/cotelettes/"
                server_url: "http://192.168.22.22/"
                login_path: /login
                check_path: /login_facebook_check
                default_target_path: /
                provider: my_facebook_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/checkout/validation, role: ROLE_USER}
        - { path: ^/monmagasin/, role: ROLE_SHOP}
        - { path: ^/category/, role: ROLE_ADMIN}
        - { path: ^/cron-manager/, role: ROLE_ADMIN}

    role_hierarchy:
        ROLE_SHOP:       ROLE_USER
        ROLE_ADMIN: ROLE_SHOP
