<?php

namespace PiggyBox\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllByShopAndCategory($shop_id, $category_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM PiggyBoxShopBundle:Product p WHERE (p.shop=:shop_id AND p.category=:category_id)')
            ->setParameters(array(
                'shop_id' => $shop_id,
                'category_id' => $category_id,
                ))
            ->getResult();
    }
}
